<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SEARCH Asset Name</name>
   <tag></tag>
   <elementGuidId>f89bc4fd-de4a-4634-883e-222269a1eeca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch' and @ref_element = 'Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>854d079d-1dce-4858-9a0e-ff46882fc402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>db9d1e36-3717-4470-b956-4b76bba6c199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>505c9319-f0ae-4b23-9b1d-ea0e4b627ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupAssetSchm$uclAssetSchm$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>0ea83986-d6ba-41c2-8fba-05ab0a3f0632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>06aea6c0-422e-4c34-a3d9-d9b6328e7fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>a13edd05-ea2a-498a-adef-5b672874ecb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>48277617-6322-4f97-b4bf-9612e6485546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>e9c18c17-cec2-46e7-8804-a9cd8c7bd719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>34454548-2a1d-42eb-a45d-61b634415168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SEARCH')])[2]</value>
      <webElementGuid>ac924968-094f-444d-a419-2be66ed3a90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Name'])[2]/following::a[1]</value>
      <webElementGuid>bb74e265-7e4b-496d-88e9-ef48960e1b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOOK UP - Asset Lookup'])[1]/following::a[1]</value>
      <webElementGuid>1e6f61fb-d429-46ec-a936-001d45549d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[2]/preceding::a[1]</value>
      <webElementGuid>83cb3dae-e121-4d49-948a-df32b7435bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Name'])[3]/preceding::a[2]</value>
      <webElementGuid>0757a9c4-eaa3-4b9f-b77a-c1ded7704120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupAssetSchm$uclAssetSchm$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>18c0553e-5cd3-42e9-a01a-8d976949d254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[2]/div/div/div/div/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>f780ab27-818c-4eea-b8d1-b7ee072dbf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupAssetSchm$uclAssetSchm$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>b3d961ea-9a1a-43ce-9187-817ab6868ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
