<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Asset</name>
   <tag></tag>
   <elementGuidId>af076370-45ac-4e56-b012-c3addb068211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetSchm_uclAssetSchm_imb</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ucLookupAssetSchm_uclAssetSchm_imb' and @ref_element = 'Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupAssetSchm_uclAssetSchm_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27640043-4ecf-4bea-a3d8-fd2585aebff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>6ab598ef-583a-4f27-9b6b-d8a98c04283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupAssetSchm$uclAssetSchm$imb</value>
      <webElementGuid>a00a46cd-8526-474e-a241-5f91f25655a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetSchm_uclAssetSchm_imb</value>
      <webElementGuid>4a7d6daa-8d77-4127-8d65-b32863c49a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>eaabe211-8e16-4869-a2a6-8d03f8ae4e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupAssetSchm_uclAssetSchm');</value>
      <webElementGuid>e12f171d-fd0a-4a7e-b802-3ec189214591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetSchm_uclAssetSchm_imb&quot;)</value>
      <webElementGuid>d819e0f4-3ec2-4a15-8c87-281ea0447c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>825f87f9-70ff-4fe0-9213-6dc0dcd4e557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupAssetSchm_uclAssetSchm_imb']</value>
      <webElementGuid>296c4efe-56b0-4bfb-97f7-46dbc342e4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainAss']/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>3bf64c69-c973-4649-a8a3-4fedf2fbd26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>9609b522-a580-4e8c-9cbf-2ac9d226ec76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupAssetSchm$uclAssetSchm$imb' and @id = 'ucLookupAssetSchm_uclAssetSchm_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>d8f0e4f8-2acf-4615-8dff-7e2fab1ca79e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
