<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Asset Name</name>
   <tag></tag>
   <elementGuidId>fc12ddcc-3afb-4baf-b1eb-ed192686252e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0' and @ref_element = 'Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6e892ff-a1bd-47d2-8a79-04a08f3032eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>3a440654-7ad4-41f4-9aab-d36fae3f9d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:AssetSchm('ucLookupAssetSchm_uclAssetSchm_txt','ucLookupAssetSchm_uclAssetSchm_hd1','APPKTM GAJAH GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd2','GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd3','967','ucLookupAssetSchm_uclAssetSchm_hd4','31','ucLookupAssetSchm_uclAssetSchm_hd5','21591');;overlay('mdnucLookupAssetSchm_uclAssetSchm');__doPostBack('mdnucLookupAssetSchm_uclAssetSchm', '')</value>
      <webElementGuid>d77dfdd7-8518-42e2-acd2-874bc41fc71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>677ea4c5-8268-4bd9-8e2e-247f09c7db6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>674b3d1b-5d22-41f3-b5d6-544b96b4c83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Asset/iframe_Term  Condition_appForm</value>
      <webElementGuid>553b51b0-20f8-4207-9be6-83e2c2b09e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>b146e251-35c5-4182-9c78-22b1bea8dcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>80d4759d-bf80-4f88-8501-abdea9642dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>ebff7105-92d7-4fb5-a8a8-aea332c91229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPKTM GAJAH GAJAH 200 DP 1.8 M'])[1]/following::a[1]</value>
      <webElementGuid>b1c38338-db87-4c9d-afde-8a931831ab75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[2]/following::a[1]</value>
      <webElementGuid>d23074c7-c047-4b95-9e46-6eedc7152d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APRILIA SR GT 200'])[1]/preceding::a[1]</value>
      <webElementGuid>3361ac6b-2006-4004-933e-1dbe58c3e372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::a[1]</value>
      <webElementGuid>f4dd8c8a-0c54-4a4a-a9c3-f7e43fefb189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>8150351a-229d-4483-ad31-92040f4a7c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:AssetSchm('ucLookupAssetSchm_uclAssetSchm_txt','ucLookupAssetSchm_uclAssetSchm_hd1','APPKTM GAJAH GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd2','GAJAH 200 DP 1.8 M','ucLookupAssetSchm_uclAssetSchm_hd3','967','ucLookupAssetSchm_uclAssetSchm_hd4','31','ucLookupAssetSchm_uclAssetSchm_hd5','21591');;overlay('mdnucLookupAssetSchm_uclAssetSchm');__doPostBack('mdnucLookupAssetSchm_uclAssetSchm', '')&quot;)]</value>
      <webElementGuid>0c61523d-da74-4530-9c14-1e5782e1c29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>08b65148-8ff5-410a-938b-35a8ea9eaf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupAssetSchm_uclAssetSchm_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:AssetSchm(&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;APPKTM GAJAH GAJAH 200 DP 1.8 M&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;GAJAH 200 DP 1.8 M&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;967&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;31&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetSchm_uclAssetSchm_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;21591&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupAssetSchm_uclAssetSchm&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupAssetSchm_uclAssetSchm&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>d83ade9f-1346-4a33-9de6-1b14a4a3b2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
