<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select Asset Name</name>
   <tag></tag>
   <elementGuidId>99139372-0faf-40d0-ac57-c86de3ba3cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Select&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>307f6dd8-37a6-4178-925d-6dbd7b7caf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>c026a241-a73f-4496-a97e-b0b32513e24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Master('ucLookupAssetMaster_uclMaster_txt','ucLookupAssetMaster_uclMaster_hd1','TOYOTA ALL NEW AVANZA VELOZ Q CVT ','ucLookupAssetMaster_uclMaster_hd2','VELOZ Q CVT ','ucLookupAssetMaster_uclMaster_hd3','778','ucLookupAssetMaster_uclMaster_hd4','1','ucLookupAssetMaster_uclMaster_hd5','21927');;overlay('mdnucLookupAssetMaster_uclMaster');__doPostBack('mdnucLookupAssetMaster_uclMaster', '')</value>
      <webElementGuid>3cc8dfc4-d3fc-495c-aa3c-253e1b4317e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>d5e32e1d-dacc-465f-be5d-4460f56473ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>1131153d-8f02-4a8e-a38c-b731e510317f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>de21b816-6188-47df-ae53-f3eec9b0dccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>f1be8fea-059d-49ea-9e55-88ff3580f292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_gvL']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>e4eeeda1-6eed-4554-8e98-b534196a2ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>f11fc98c-e676-4110-b85e-dc6a3ee4ff98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA ALL NEW AVANZA VELOZ Q CVT'])[1]/following::a[1]</value>
      <webElementGuid>62857123-3cf4-4b6a-82f8-ce98c15ad221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[1]/following::a[1]</value>
      <webElementGuid>6847fcc2-b615-4dfc-ab7f-5c74f27ea597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>42a39b65-3ece-4dfb-884d-591fe415e807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>640f1de2-38a9-4f70-b919-4eecff6d5c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:Master('ucLookupAssetMaster_uclMaster_txt','ucLookupAssetMaster_uclMaster_hd1','TOYOTA ALL NEW AVANZA VELOZ Q CVT ','ucLookupAssetMaster_uclMaster_hd2','VELOZ Q CVT ','ucLookupAssetMaster_uclMaster_hd3','778','ucLookupAssetMaster_uclMaster_hd4','1','ucLookupAssetMaster_uclMaster_hd5','21927');;overlay('mdnucLookupAssetMaster_uclMaster');__doPostBack('mdnucLookupAssetMaster_uclMaster', '')&quot;)]</value>
      <webElementGuid>7b2867d4-474e-4c40-b962-225fcd7e7063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>ce723ac7-5989-4255-8609-8f76cd969f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:Master(&quot; , &quot;'&quot; , &quot;ucLookupAssetMaster_uclMaster_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetMaster_uclMaster_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;TOYOTA ALL NEW AVANZA VELOZ Q CVT &quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetMaster_uclMaster_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;VELOZ Q CVT &quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetMaster_uclMaster_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;778&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetMaster_uclMaster_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupAssetMaster_uclMaster_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;21927&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupAssetMaster_uclMaster&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupAssetMaster_uclMaster&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>55deca2a-9e79-4a99-8e1a-e384a96ca4cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
