<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select City Name</name>
   <tag></tag>
   <elementGuidId>ca5554a8-93e7-4e0b-94e9-16f8e54e1efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Select&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>039a1e19-f14b-47ae-a49f-f7bd3a22d53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>31a5656b-fd70-4584-91bf-ebfd1b7ac0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CityLookup('ucLookupCity_uclCity_hd1','0393','ucLookupCity_uclCity_hd2','3465','ucLookupCity_uclCity_txt','ucLookupCity_uclCity_hd3','Jakarta Barat, Wil. Kota');;overlay('mdnucLookupCity_uclCity');__doPostBack('mdnucLookupCity_uclCity', '')</value>
      <webElementGuid>4d061667-7e91-411b-81e9-cace0035ef54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>f7102e2e-e531-4d6d-beb6-710e94e0024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>2a8679b3-641f-48ce-8579-9f840fd3a446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>89f2a298-ae84-475b-9a50-839bdae44d40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>0549277c-8922-4233-ae49-3252570edec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupCity_uclCity_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>0c920d0e-69fc-4394-a8aa-5bf19c5269f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>19b02ae2-30e7-41db-b472-2926fd454b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Barat, Wil. Kota'])[1]/following::a[1]</value>
      <webElementGuid>ebd8defa-063c-42d2-b844-dfcfd4088f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[2]/following::a[1]</value>
      <webElementGuid>b5410d1f-6c23-44d5-bf7a-0f29cf25dc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[2]/preceding::a[1]</value>
      <webElementGuid>7f71ad75-8758-4ae1-a69d-dd2f596b2324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>15c18a8f-f38c-4452-b242-6d2b02242de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CityLookup('ucLookupCity_uclCity_hd1','0393','ucLookupCity_uclCity_hd2','3465','ucLookupCity_uclCity_txt','ucLookupCity_uclCity_hd3','Jakarta Barat, Wil. Kota');;overlay('mdnucLookupCity_uclCity');__doPostBack('mdnucLookupCity_uclCity', '')&quot;)]</value>
      <webElementGuid>1ebd3efb-da45-4cc3-b209-cc0adf6828a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>f7c065dd-2e48-4fb4-a34e-0ec1dedff663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupCity_uclCity_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CityLookup(&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;0393&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;3465&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupCity_uclCity_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Jakarta Barat, Wil. Kota&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupCity_uclCity&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupCity_uclCity&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>13d38fb6-6a65-4b9d-b77f-97e03dc0fa7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
