<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Collateral Price</name>
   <tag></tag>
   <elementGuidId>cb8425b5-d700-4136-ae39-9144e18c213b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAssetPrice_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAssetPrice_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucAssetPrice_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e837a187-59b9-4765-91d2-8e5b388e634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAssetPrice$txtInput</value>
      <webElementGuid>4bc7b4d7-c009-4c50-9372-7e5c06e21b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efb83d7a-5c09-4fb0-8620-7d35b72b20d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>05d79473-1294-4c4d-8c35-f226b697d000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAssetPrice_txtInput</value>
      <webElementGuid>c2b78a33-5cec-4d3f-943d-c613ca2b93bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>0bb84d25-2366-4617-a7fc-0b85efb80ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucAssetPrice_txtInput','ucAssetPrice_hdnInput','ucAssetPrice_txtInputDummy');</value>
      <webElementGuid>2e0a5483-24f4-48ec-9786-9f6ca862d270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucAssetPrice_txtInput');</value>
      <webElementGuid>3faea9c6-be14-40ca-8c63-b7765bae5637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>f0d0c7c9-d238-4bda-bff1-bcd3e3de68e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAssetPrice_txtInput&quot;)</value>
      <webElementGuid>6dcbe542-f83a-499a-b88f-b0bd8f038070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>3836bb4f-82c1-4dbb-a50d-9340f34a3d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAssetPrice_txtInput']</value>
      <webElementGuid>4eb94dd0-74e7-4bfa-b537-16fc659456f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainAss']/table/tbody/tr[4]/td[2]/input[2]</value>
      <webElementGuid>820471db-fdbe-4980-924d-34d8605278b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input[2]</value>
      <webElementGuid>b4aaf1ba-3e1a-4907-9863-cac3bde3c715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAssetPrice$txtInput' and @type = 'text' and @id = 'ucAssetPrice_txtInput']</value>
      <webElementGuid>e7953147-baa8-4cd2-9d14-36aff66812ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
