<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Rangka</name>
   <tag></tag>
   <elementGuidId>4bacb2e9-f04b-450b-a9db-dc80848c3c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSerialNo1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSerialNo1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;txtSerialNo1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef6c47dd-b4b7-4c31-8c24-169786edc3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSerialNo1</value>
      <webElementGuid>bc1556bf-6faf-4aa6-aebd-c80cfa614af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d581b914-11e5-4b04-a3af-e6e330db6190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSerialNo1</value>
      <webElementGuid>d33ce10d-b995-4d99-8785-a386cfda74da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>b953101f-6b41-485a-aa27-d9a6610ab09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSerialNo1&quot;)</value>
      <webElementGuid>cb2c2444-e55a-4fea-b21f-7fe6b0022f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>70c5898e-1787-48e1-a0bf-17cedd3cc89c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSerialNo1']</value>
      <webElementGuid>71106e7d-6717-4e73-b291-862e9c064230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAssetData']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8ba8d427-fa22-44d3-87db-e277ebe21cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a8409b8c-5843-4ace-ad35-d92a4e0196d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtSerialNo1' and @type = 'text' and @id = 'txtSerialNo1']</value>
      <webElementGuid>5a2d4306-e26c-41a5-8b7e-e61a46849232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
