<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City Name</name>
   <tag></tag>
   <elementGuidId>10932331-7b1a-42b4-a039-8dd82ea25370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15948b0a-2f5b-4917-a4b9-a560d4a6e82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupCity$uclCity$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue</value>
      <webElementGuid>7ec324c2-fb4d-4cd3-be33-1fa4418369a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f8344da-333c-462d-bdaf-6c9cd01ea6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      <webElementGuid>6ad0cfd3-57a7-4b8d-9edd-ec57ecd0450b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>08a43db0-ac1d-4cf0-88ea-b76b032bff0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1&quot;)</value>
      <webElementGuid>2972d1da-f4d6-4f6b-bc63-946f4ee0328a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>41eac7a8-7bca-44db-9516-6a55dccb4788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>1b616eb1-31c9-410a-894e-01f7fd855f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupCity_uclCity_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1c32091f-2b38-493b-8f77-d25bd7a9b7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>fdbfa1b0-e055-424a-913c-16f7f714a78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucLookupCity$uclCity$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue' and @type = 'text' and @id = 'ucLookupCity_uclCity_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>97964461-4c68-47f3-97d0-696874f04b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
