<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_License Plate No</name>
   <tag></tag>
   <elementGuidId>8a5409e3-07b0-46c2-9fe2-a306a8ddfda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLicensePlateNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLicensePlateNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtLicensePlateNo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5130be27-c57a-4247-8485-965324f2a1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLicensePlateNo</value>
      <webElementGuid>363a0efc-ea6c-40a9-bdef-acfd3549cca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e32d881-51c1-474c-878b-5ca85b7e101c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLicensePlateNo</value>
      <webElementGuid>93c4affc-e031-4736-a649-889b6d6a726f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>5c28739c-3b66-4cc7-8f5c-b36b6ceefda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLicensePlateNo&quot;)</value>
      <webElementGuid>96f22c30-9389-410e-974a-5f17b2ce63c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>6ba8e2ff-39fb-4fcc-83f4-f6c6c4282e24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLicensePlateNo']</value>
      <webElementGuid>371c1b12-7dc8-4254-ab10-1f7da022f1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trLicensePlate']/td[2]/input</value>
      <webElementGuid>5c260f6c-98fd-41f8-9e3a-5f1ea84f9dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>8bbe9db3-b2cd-4c10-89af-3781aebef444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtLicensePlateNo' and @type = 'text' and @id = 'txtLicensePlateNo']</value>
      <webElementGuid>75e97f7e-efa7-4a58-b28a-f907d8f9d4d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
