<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asset Name</name>
   <tag></tag>
   <elementGuidId>80e5bf03-7a68-4bcc-ba77-38638e20c91e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>680023c8-dc32-4fd8-a40f-22e8131816c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupAssetMaster$uclMaster$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue</value>
      <webElementGuid>46c89f8a-a85e-42a0-99d1-db6a8ca55b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>546a746e-5ce9-4b21-9904-a9ac1ce1ba06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      <webElementGuid>4c5a96b7-94a5-43c0-82bb-7bc60a94747d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>b6a4806d-5e62-42b0-9777-47167916f786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0&quot;)</value>
      <webElementGuid>90b2bf52-8e1b-4964-abd4-8c66fcd321bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>6a9b9ec1-c08d-49de-b613-af84ec64e322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>3b25b2d8-6d7b-4e98-8c70-73f9ab73ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>234016b7-5373-4534-a5e6-ae1c3d076778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c2af3781-176c-47a1-83a6-03731741f41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucLookupAssetMaster$uclMaster$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue' and @type = 'text' and @id = 'ucLookupAssetMaster_uclMaster_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>6b3058d7-9b9b-4a51-bad7-fecc323ea811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
