<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manufacturing Year</name>
   <tag></tag>
   <elementGuidId>ccf28d4a-a556-44ef-98d2-094ef6e6fe7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtManufacturingYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtManufacturingYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtManufacturingYear</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7273ece-5b0e-49cf-a468-42b1eadfd94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtManufacturingYear</value>
      <webElementGuid>7eda820c-edb4-43ee-894e-14d89043a9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>191469e1-3aef-4bdc-a61d-73922b4577f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0ddbeebf-1b5d-4dc5-ac0f-cac11b8f6542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'txtManufacturingYear\',\'\')', 0)</value>
      <webElementGuid>5d2e04e6-8717-4666-9c00-5f9bfebfff0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return isNumberKey(event)</value>
      <webElementGuid>b5ad60c1-467b-464b-88f3-dae632e49805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtManufacturingYear</value>
      <webElementGuid>c1ae2fb7-081c-40ae-8ff2-b308ffd4c656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
      <webElementGuid>a42dd9ec-bbdb-4c2c-91dd-9c1f9ab4ddda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtManufacturingYear&quot;)</value>
      <webElementGuid>4b36d9f9-c893-4570-868b-4609529ab958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Collateral Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>19193227-7c78-4246-b41f-aa4319f7453d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtManufacturingYear']</value>
      <webElementGuid>d0e4b252-c490-480f-a50e-6f4d2a163a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainAss']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>82b17c9a-5f2e-43de-886a-334b25ddd493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>c71909c2-8515-48e3-9997-ed1fe30c9b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtManufacturingYear' and @type = 'text' and @id = 'txtManufacturingYear']</value>
      <webElementGuid>4dcc39e1-6ca6-46c3-9a6d-0e66ebb280cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
