<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Del Commision supplier</name>
   <tag></tag>
   <elementGuidId>499e9bb0-0abd-4533-9f61-13ed2c3117fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSupplCommission_ibDelSuppl_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplCommission_ibDelSuppl_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvSupplCommission_ibDelSuppl_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplCommission_ibDelSuppl_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eff6bf6c-5d5e-4329-b8ed-e48cd931d3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>cc0cd928-7a8c-4a4b-ac68-5f8967299f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplCommission$ctl02$ibDelSuppl</value>
      <webElementGuid>05306a10-5dd4-4c5f-b362-5579a6724dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplCommission_ibDelSuppl_0</value>
      <webElementGuid>8e1ea9d4-f4d5-40c0-97fd-7592e8e0c256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Record</value>
      <webElementGuid>6b51a5de-4496-47d8-ac48-02eabb67b2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Delete.gif</value>
      <webElementGuid>facac185-f946-4576-a5c4-d6d5864b25f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure want to delete this record');</value>
      <webElementGuid>7df05e7e-bc68-4e79-a4e8-d30baa309960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplCommission_ibDelSuppl_0&quot;)</value>
      <webElementGuid>e6fccf1c-9a9f-40d6-b82f-ffb15e33634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>5989a30d-e1d9-48eb-947e-4ed5ffb52d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplCommission_ibDelSuppl_0']</value>
      <webElementGuid>b2153d48-0685-4d03-9aae-32a072751b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplCommission']/tbody/tr[2]/td[6]/input</value>
      <webElementGuid>746a16f7-5a85-4799-9917-18c5e2ba536a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>b3256dd0-154b-4061-a485-f257d0252bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSupplCommission$ctl02$ibDelSuppl' and @id = 'gvSupplCommission_ibDelSuppl_0' and @title = 'Delete Record' and @src = '../../../../Images/Delete.gif']</value>
      <webElementGuid>13ecfaca-652e-4f75-9b24-2b8ee8603bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
