<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Del Commsion employee</name>
   <tag></tag>
   <elementGuidId>1dc13b32-5d80-4b2c-b4c0-cbfec61b9efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSupplEmpCommission_ibDelSupplEmp_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplEmpCommission_ibDelSupplEmp_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvSupplEmpCommission_ibDelSupplEmp_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplEmpCommission_ibDelSupplEmp_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2354004-a71c-4e83-97e7-7cfd98e258bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>59da4672-692d-4268-938f-ea83b388b360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplEmpCommission$ctl02$ibDelSupplEmp</value>
      <webElementGuid>a167e69c-8766-46c6-a696-c30d7bbaab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplEmpCommission_ibDelSupplEmp_0</value>
      <webElementGuid>c5507354-77ec-4800-8840-0d9411e3ef82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete Record</value>
      <webElementGuid>7c447445-02af-4e98-b68c-5f650d2d1076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Delete.gif</value>
      <webElementGuid>61af83da-9933-4bc4-82dd-38ca0f71fbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure want to delete this record');</value>
      <webElementGuid>f30a4516-ee43-4945-bffb-0feb88763477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplEmpCommission_ibDelSupplEmp_0&quot;)</value>
      <webElementGuid>d9061a71-fd29-467c-9d91-d01b8e79b072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>4f5ab9fa-9014-42db-865e-7c1c67ddf997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplEmpCommission_ibDelSupplEmp_0']</value>
      <webElementGuid>b0bf2fc1-40aa-4d0a-9776-894c0d78e1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplEmpCommission']/tbody/tr[2]/td[7]/input</value>
      <webElementGuid>ccadc1cc-202b-475f-863e-a1c3fb59a23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>a0e8c89b-3d3e-4a1e-b071-07a6a567f521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSupplEmpCommission$ctl02$ibDelSupplEmp' and @id = 'gvSupplEmpCommission_ibDelSupplEmp_0' and @title = 'Delete Record' and @src = '../../../../Images/Delete.gif']</value>
      <webElementGuid>a36eb812-b897-4dea-af00-b263350d5002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
