<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employee Commission</name>
   <tag></tag>
   <elementGuidId>a2642f0b-b2e8-47b0-8457-f2033e000bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed2b54f4-cd24-4059-91da-4a542a286a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplEmpCommission$ctl02$ucinCommissionAmt2$txtInput</value>
      <webElementGuid>cc6c2721-e3f6-410c-8b6f-da8fd863e321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1752df2a-6714-474f-a56b-1a58bcea0bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>a97472a7-78e3-42ba-8fea-8fd86bf2c6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvSupplEmpCommission$ctl02$ucinCommissionAmt2$txtInput\',\'\')', 0)</value>
      <webElementGuid>b2238502-3207-485f-8483-d767691194fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>142ff226-b8a9-408e-9e42-2b4879cc9373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0</value>
      <webElementGuid>d5ec505d-d884-4e47-8f4d-25545f3dafc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>6dc332cc-8030-45b5-b8ea-4be7e8c21818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0','gvSupplEmpCommission_ucinCommissionAmt2_0_hdnInput_0','gvSupplEmpCommission_ucinCommissionAmt2_0_txtInputDummy_0');</value>
      <webElementGuid>a8dfae39-fae8-483d-aefd-2db34350a0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0');</value>
      <webElementGuid>c39a4532-b399-4f00-9ef4-cef34e144720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0&quot;)</value>
      <webElementGuid>9a6cbfcb-8367-4f30-abda-039220468bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>d4ee6fb5-d4da-4984-b5a1-1c2793206156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0']</value>
      <webElementGuid>935f7792-ec43-45c5-9a8c-9960ee233711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplEmpCommission']/tbody/tr[2]/td[3]/input[2]</value>
      <webElementGuid>7cddf487-7c20-46ad-b0c2-8de8cdd4d5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input[2]</value>
      <webElementGuid>ff6a9a43-73d4-4858-a36b-9e3886325787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvSupplEmpCommission$ctl02$ucinCommissionAmt2$txtInput' and @type = 'text' and @id = 'gvSupplEmpCommission_ucinCommissionAmt2_0_txtInput_0']</value>
      <webElementGuid>aafdca38-a505-48c8-9d14-ea86ca08d521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
