<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Supplier Commission</name>
   <tag></tag>
   <elementGuidId>7940cd95-5634-4814-b472-e583a648609e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSupplCommission_ucinCommissionAmt_0_txtInput_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSupplCommission_ucinCommissionAmt_0_txtInput_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvSupplCommission_ucinCommissionAmt_0_txtInput_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvSupplCommission_ucinCommissionAmt_0_txtInput_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0169d13-7aa1-4f8c-830a-4fb217b58c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSupplCommission$ctl02$ucinCommissionAmt$txtInput</value>
      <webElementGuid>7ac89cd9-4f0c-488d-bfc8-3889d82cb1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9f696f0-88a2-4fb5-b855-7e9a193e9cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>ea0d11b2-3084-40e9-b34b-fa5b16d91832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvSupplCommission$ctl02$ucinCommissionAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>2b7a3140-275b-4748-8a24-334d078ced61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>f15d1d4f-dbcc-464f-8931-e70a16105c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSupplCommission_ucinCommissionAmt_0_txtInput_0</value>
      <webElementGuid>5cf3e6f6-40c4-4aa2-b3de-c97e7144d601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>f8562c2a-7de1-489e-9bce-a1d860457504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('gvSupplCommission_ucinCommissionAmt_0_txtInput_0','gvSupplCommission_ucinCommissionAmt_0_hdnInput_0','gvSupplCommission_ucinCommissionAmt_0_txtInputDummy_0');</value>
      <webElementGuid>39db9fe8-af75-49dd-86a3-dfd777b55220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('gvSupplCommission_ucinCommissionAmt_0_txtInput_0');</value>
      <webElementGuid>2c608cc0-5723-405e-b20a-b97b8ac1d6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvSupplCommission_ucinCommissionAmt_0_txtInput_0&quot;)</value>
      <webElementGuid>733e206b-7989-47a9-ac4b-4ceacab62b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Commision data/iframe_Term  Condition_appForm</value>
      <webElementGuid>ace97ca3-6524-4a2b-8257-aa57b1330457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSupplCommission_ucinCommissionAmt_0_txtInput_0']</value>
      <webElementGuid>34787858-8c3c-4593-88e8-92a102f621f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSupplCommission']/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>ed8af60b-7036-486b-aeb8-38c968e426cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>066a0758-6ff4-4e55-a688-da0ab016cdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gvSupplCommission$ctl02$ucinCommissionAmt$txtInput' and @type = 'text' and @id = 'gvSupplCommission_ucinCommissionAmt_0_txtInput_0']</value>
      <webElementGuid>bbca9cba-37e9-456b-ab9b-89e12c99f20a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
