<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Loan data</name>
   <tag></tag>
   <elementGuidId>e3fa2df5-bee7-4a6c-8556-9e768adfaa0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_AgrmntLoanData_Add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_AgrmntLoanData_Add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec400a32-af20-4869-afd5-732b1bb3da64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>73146442-69d1-4c70-9e90-9748aadcb40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_AgrmntLoanData_Add</value>
      <webElementGuid>c9970cad-cd66-4132-bcd3-62c94ac670d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>f6ec2497-2692-48a3-b67d-fd319caece88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_AgrmntLoanData_Add&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>f6204a49-4450-4c5e-98b3-f1968c42cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_AgrmntLoanData_Add</value>
      <webElementGuid>f783c618-3d8f-4914-a47c-b323a3275e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>6953ea85-f366-4664-a21f-85e6aa1532f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_AgrmntLoanData_Add&quot;)</value>
      <webElementGuid>2629f0f8-24c6-450a-b7e5-fc73e34f106c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>e1c99df2-0f1b-4f0c-a9aa-10b36cc6a9f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_AgrmntLoanData_Add']</value>
      <webElementGuid>ee61bf0a-6c65-4dc6-8421-3b174471e264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMenuAdd']/span/input</value>
      <webElementGuid>27aea7fc-dffb-4bed-9cff-be12817c43f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>18e09ee2-4328-4f3e-b59d-40a28a9bdf72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_AgrmntLoanData_Add' and @id = 'lb_AgrmntLoanData_Add']</value>
      <webElementGuid>4e6590b9-dfba-4022-a3e1-2812739c8745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
