<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank Tidak</name>
   <tag></tag>
   <elementGuidId>568e47ea-4615-47bb-81b5-7c286a849978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblInputBankAcc_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblInputBankAcc_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;No&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3334217d-2375-4f44-972e-22d03eeab5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblInputBankAcc_1</value>
      <webElementGuid>324bccc9-a77a-44c7-9eb5-74ad606ed523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>aec8f502-633b-4d6e-9b5c-3b21bf087b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblInputBankAcc</value>
      <webElementGuid>393a124d-1832-498f-849a-e4fb295506f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>2a7225fa-80cd-49d0-adca-fbeccde80501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'rblInputBankAcc$1\',\'\')', 0)</value>
      <webElementGuid>ad8dd301-b7c4-47f4-8a21-887b3708a377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblInputBankAcc_1&quot;)</value>
      <webElementGuid>33c8e8ed-34ea-402b-9a38-5b449db8733c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>3b05ef98-4d70-4ded-845f-81d47d22c6df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblInputBankAcc_1']</value>
      <webElementGuid>81e9277c-ffd8-41d8-af50-176c74142e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblInputBankAcc']/tbody/tr/td[2]/input</value>
      <webElementGuid>90521016-9f78-4d8c-8fc9-a28fef5eb83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>70eba1bc-0860-475c-a6f3-169752da9fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblInputBankAcc_1' and @type = 'radio' and @name = 'rblInputBankAcc']</value>
      <webElementGuid>49ff195a-0658-4362-a89c-8a79388d790b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
