<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank Ya</name>
   <tag></tag>
   <elementGuidId>56b1d21c-0390-4ee7-b73e-899675ff30d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblInputBankAcc_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblInputBankAcc_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Yes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0dce322-a73b-4a14-849a-3715ad47faa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblInputBankAcc_0</value>
      <webElementGuid>1f9057fc-56c9-4919-b5c4-a5c31cf8b426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b5a53488-294c-4056-94b7-a3fad67d2a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblInputBankAcc</value>
      <webElementGuid>33e9ceb6-0c6b-43dc-9a63-ac906a8859e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>7262c94b-1751-4b9b-8060-3d96557ae3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>ef3a4afe-79e1-49cb-955b-339329e19b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblInputBankAcc_0&quot;)</value>
      <webElementGuid>4dd7d894-4d3d-48ec-b836-a773270acbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>2761a7af-0b2c-4d01-9233-78272d038870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblInputBankAcc_0']</value>
      <webElementGuid>05e06715-ce11-47e6-8d11-ee9cbe4beab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblInputBankAcc']/tbody/tr/td/input</value>
      <webElementGuid>7fc69751-dcb4-443b-b12c-4a25c34ac0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>8e64287c-70ee-4a29-b30d-dc67f96fe6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblInputBankAcc_0' and @type = 'radio' and @name = 'rblInputBankAcc' and @checked = 'checked']</value>
      <webElementGuid>7da3aca6-864f-4722-8fd3-7ac975bed76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
