<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Search Bank Name</name>
   <tag></tag>
   <elementGuidId>2056ed7b-31ee-4dbe-b15e-11294f2a89c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucBankAcc_ucLookupBank_uclBank_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucBankAcc_ucLookupBank_uclBank_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucBankAcc_ucLookupBank_uclBank_imb</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c493d3f0-750f-489f-a94f-3fcd2af3efcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1ebd36b3-db73-4e7d-8cda-50d699ffda36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucBankAcc$ucLookupBank$uclBank$imb</value>
      <webElementGuid>06911136-0da6-4395-b956-59755b9de1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucBankAcc_ucLookupBank_uclBank_imb</value>
      <webElementGuid>9ac5f794-ccfa-42bb-a193-e2df2c6edb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>c44ba153-b0d6-4fd2-8cb3-1d2d978623a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucBankAcc_ucLookupBank_uclBank');</value>
      <webElementGuid>38062199-a3c7-443d-b743-8a04db9aa66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucBankAcc_ucLookupBank_uclBank_imb&quot;)</value>
      <webElementGuid>8e48fb40-fde1-4551-9592-df148bc31834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>e0a78466-94dc-4fc5-8730-64da7985d347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucBankAcc_ucLookupBank_uclBank_imb']</value>
      <webElementGuid>17e55bb0-1aa1-4e41-ab3b-ce95979bd1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucBankAcc_ucBank']/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>46a485a0-add5-44d2-bd0e-1203eb910d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>21eec92c-5ae0-4ffe-9a3e-057ab6501293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucBankAcc$ucLookupBank$uclBank$imb' and @id = 'ucBankAcc_ucLookupBank_uclBank_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>c3e11c97-fcd5-4059-9dbd-82c9a227e5a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
