<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Search Disburse to</name>
   <tag></tag>
   <elementGuidId>2d6d5655-2b83-4274-9847-61c9aa4f4641</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplierBranch_uclSupplBranchSchmX_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucLookupSupplierBranch_uclSupplBranchSchmX_imb</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dc9cb0d-22dd-4279-810f-af2a95e24eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>108bfdf4-e588-4e6a-b96d-d0b84ba3567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupSupplierBranch$uclSupplBranchSchmX$imb</value>
      <webElementGuid>b8a75850-691a-4fad-8767-b04b7310e477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplierBranch_uclSupplBranchSchmX_imb</value>
      <webElementGuid>b3851125-c439-430c-aba6-0e9f465b82d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>9ccedde2-d170-4317-a504-85bae5296235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupSupplierBranch_uclSupplBranchSchmX');</value>
      <webElementGuid>dca3dab4-aabb-40e3-9f0e-f93088e97be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplierBranch_uclSupplBranchSchmX_imb&quot;)</value>
      <webElementGuid>ba3192c0-42ce-4ad1-8df8-cbbecae873e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>ed04aec2-704b-4f0e-8a36-d8401b611d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_imb']</value>
      <webElementGuid>88070995-1dd6-4256-a6eb-6fde2e2648c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAddEdit']/table/tbody/tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>90623666-8c0c-45e4-8bfd-9904baf41cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>0cae5f58-89d0-4364-bb00-bceb2ccfe9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupSupplierBranch$uclSupplBranchSchmX$imb' and @id = 'ucLookupSupplierBranch_uclSupplBranchSchmX_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>bb6bcc4b-b91b-472a-8479-dc8b51356db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
