<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</name>
   <tag></tag>
   <elementGuidId>6bd608cd-ef49-4950-ad2b-50bb8efcd38d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainPage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e24e8358-f862-43aa-9afc-3736b565b415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>eaacb524-f926-47fd-841b-19f74d01e982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>a08650dc-03d9-476d-a9da-656b9acb2e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e0d623d5-bd15-4695-8d80-d5c28e3bc8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.aspx?BLCODE=PMCFJASA</value>
      <webElementGuid>57490459-f8cf-459b-9759-dae2752e2092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPage&quot;)</value>
      <webElementGuid>0e2d02eb-92f6-4f9d-87d7-12d4591836c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainPage']</value>
      <webElementGuid>2dd9b3a5-d996-43cd-b857-2c36a86179df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[3]</value>
      <webElementGuid>0cbc38b4-d5d0-47e1-bbd9-e73764747f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>cf6b0b80-f915-4768-8e7b-1054d35659b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainPage' and @name = 'mainPage' and @src = 'LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.aspx?BLCODE=PMCFJASA']</value>
      <webElementGuid>b76be159-6c19-4b97-9052-4aaf5b181cb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
