<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier Branch Name</name>
   <tag></tag>
   <elementGuidId>8d83da3d-55f2-4f0a-ba82-523a8fed7032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b94e4b3-65ab-4b47-9f31-cb6380b0b7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupSupplierBranch$uclSupplBranchSchmX$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue</value>
      <webElementGuid>b370d00a-d2f5-4def-a8a8-dcae9be6cfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d810fb0-6584-4f0e-83e5-ec2882af2664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      <webElementGuid>1061f418-b9b2-4329-a8f7-959b4bf2c106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>be0e1b08-b44e-43fc-8462-82c89902eb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0&quot;)</value>
      <webElementGuid>080ff8f8-3771-49c2-884c-5d16399c3c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>3f261cba-057d-4844-8873-90b66094a759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>851dcac6-72b1-4917-bd0b-9ddab0b88ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>be47f44a-d200-43ff-8483-32b3b15089b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f6008614-9122-4788-9591-1b21bed51645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucLookupSupplierBranch$uclSupplBranchSchmX$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue' and @type = 'text' and @id = 'ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>d7e483b3-0a01-45cd-a7e3-5dd7ad8551af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
