<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Budget Plan Amount</name>
   <tag></tag>
   <elementGuidId>452aebe4-9727-487d-bee7-4ea2f2e43607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucBudgetPlanAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucBudgetPlanAmt_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucBudgetPlanAmt_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fa24d9d-dd56-4544-847d-52654f591df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucBudgetPlanAmt$txtInput</value>
      <webElementGuid>2576e3d0-a0ad-4efc-acb0-240d2fc2bc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85cd8552-c16a-4333-83ce-c9cb505cfa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>21d40716-8ae3-460e-8c6e-9c7758895390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucBudgetPlanAmt$txtInput\',\'\')', 0)</value>
      <webElementGuid>222516d1-ffb6-43a3-ae94-dc10e3bb61f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>738d4491-89ba-4b05-99f2-9d1d4ad60236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucBudgetPlanAmt_txtInput</value>
      <webElementGuid>7f71774e-158a-480d-a743-c32b1f26f754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>6294cddc-a11e-4044-ab1d-fb93d34841db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucBudgetPlanAmt_txtInput','ucBudgetPlanAmt_hdnInput','ucBudgetPlanAmt_txtInputDummy');</value>
      <webElementGuid>05eab9ee-08fc-42b3-baf0-a199c1abb75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucBudgetPlanAmt_txtInput');</value>
      <webElementGuid>3397cd1a-8719-4993-92c5-bf38f4880015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucBudgetPlanAmt_txtInput&quot;)</value>
      <webElementGuid>e9db8444-2bae-4cc9-8cec-1e2cfa3ca74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>272abde1-a2d2-4193-856b-2b297a15c954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucBudgetPlanAmt_txtInput']</value>
      <webElementGuid>d5bd1585-6a01-4d85-b92c-fbf0c456be80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAddEdit']/table[2]/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>6e3e1266-f19e-4a90-ae29-a28ca048176e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input[2]</value>
      <webElementGuid>32915e4e-0e0f-4e6f-bab3-4daf1f2db1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucBudgetPlanAmt$txtInput' and @type = 'text' and @id = 'ucBudgetPlanAmt_txtInput']</value>
      <webElementGuid>65dcbbac-dd56-4bf0-863e-6fc7b265ea76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
