<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Name</name>
   <tag></tag>
   <elementGuidId>853aaf14-dd84-4f8c-b4dc-85655d39a081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd8ee895-e459-429b-905f-8da94d968cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucBankAcc$txt_OfficeBankAcc_OfficeBankAccName</value>
      <webElementGuid>2e60c06e-d1f6-487a-b0b0-4c6681c01ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4aebc3a-c889-4d0e-ba1e-5f486b8fff56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>00858fab-b201-46bc-844a-1c7d86f2a048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName</value>
      <webElementGuid>610d0c8e-6305-45d5-ba1c-eb65bd90869c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>21b54739-719e-4f5b-85f6-a4ff2b5bede0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName&quot;)</value>
      <webElementGuid>5bedca7d-b19f-432f-8af1-fad323ec9e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>7de06ac4-6a1c-47e1-a8ae-2f7e7e145325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName']</value>
      <webElementGuid>bc8ba8b5-6225-45f3-aae7-acd5789d1e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucBankAcc_ucBank']/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>41c7ad49-7840-4d6e-a1e6-1e93af63299d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>9254178f-f2f4-4a87-9784-e12bc38852c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucBankAcc$txt_OfficeBankAcc_OfficeBankAccName' and @type = 'text' and @id = 'ucBankAcc_txt_OfficeBankAcc_OfficeBankAccName']</value>
      <webElementGuid>446529d4-f950-4314-b819-52a4cb06fa3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
