<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Supplier name</name>
   <tag></tag>
   <elementGuidId>c6ef91df-492a-465c-8e7e-5278541619d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Select&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfdc5c97-f6e8-4dc5-a3df-a0aeff32b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>1ea7fd7b-2dfb-41e5-b2e4-0d43497472e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:SupplBranchSchmLookupX('ucLookupSupplierBranch_uclSupplBranchSchmX_txt','ucLookupSupplierBranch_uclSupplBranchSchmX_hd1','BUMI SUMBER MUSTIKA, PT','ucLookupSupplierBranch_uclSupplBranchSchmX_hd2','3','ucLookupSupplierBranch_uclSupplBranchSchmX_hd3','16737','ucLookupSupplierBranch_uclSupplBranchSchmX_hd4','BUMI SUMBER MUSTIKA, PT','ucLookupSupplierBranch_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplierBranch_uclSupplBranchSchmX_hd6','JL RAYA BEKASI KM 18 NO 49','ucLookupSupplierBranch_uclSupplBranchSchmX_hd7','6/24/2028 12:00:00 AM');;overlay('mdnucLookupSupplierBranch_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplierBranch_uclSupplBranchSchmX', '')</value>
      <webElementGuid>87487c76-9f64-41b7-97a3-07a7d964c750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>71f64a5e-3125-4ad5-942c-916e629bbfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>825f4244-3264-4795-8c57-345ffbd5bddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>7c46d69c-97a0-497a-b22c-4b9dc5c9eced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>70ffcb14-0311-4581-bab0-8fc3a1e54f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>3fca4055-0793-435a-9f48-de28976e60f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>58484604-cf3b-4ae5-b355-593575cf0a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JL RAYA BEKASI KM 18 NO 49'])[1]/following::a[1]</value>
      <webElementGuid>1a38b9c7-e402-4fe7-85db-35c0f2b28bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NORMAL'])[2]/following::a[1]</value>
      <webElementGuid>91e34623-0c8a-4145-a0bd-457cb59b42b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>7e46801e-f956-4903-87a6-cbad0ad4c221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>b77dfb06-a6ed-482b-86fa-3cb3d778e83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:SupplBranchSchmLookupX('ucLookupSupplierBranch_uclSupplBranchSchmX_txt','ucLookupSupplierBranch_uclSupplBranchSchmX_hd1','BUMI SUMBER MUSTIKA, PT','ucLookupSupplierBranch_uclSupplBranchSchmX_hd2','3','ucLookupSupplierBranch_uclSupplBranchSchmX_hd3','16737','ucLookupSupplierBranch_uclSupplBranchSchmX_hd4','BUMI SUMBER MUSTIKA, PT','ucLookupSupplierBranch_uclSupplBranchSchmX_hd5','NORMAL','ucLookupSupplierBranch_uclSupplBranchSchmX_hd6','JL RAYA BEKASI KM 18 NO 49','ucLookupSupplierBranch_uclSupplBranchSchmX_hd7','6/24/2028 12:00:00 AM');;overlay('mdnucLookupSupplierBranch_uclSupplBranchSchmX');__doPostBack('mdnucLookupSupplierBranch_uclSupplBranchSchmX', '')&quot;)]</value>
      <webElementGuid>9de00949-73cd-4a06-afdf-be678955c994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>218e600e-1f4b-4701-ae78-8e91bfbc69bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupSupplierBranch_uclSupplBranchSchmX_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:SupplBranchSchmLookupX(&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;BUMI SUMBER MUSTIKA, PT&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;16737&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;BUMI SUMBER MUSTIKA, PT&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;NORMAL&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;JL RAYA BEKASI KM 18 NO 49&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSupplierBranch_uclSupplBranchSchmX_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;6/24/2028 12:00:00 AM&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupSupplierBranch_uclSupplBranchSchmX&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupSupplierBranch_uclSupplBranchSchmX&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>7e98e365-5e09-408a-ae82-0f04561786c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
