<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Bank Name</name>
   <tag></tag>
   <elementGuidId>43e3326a-7acd-48b1-9eea-8468a00370ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Select&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d27a099f-1afb-4ca8-91c5-f88de08e9e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>77087613-a7c6-438b-9936-5cc877456a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:BankLookup('ucBankAcc_ucLookupBank_uclBank_txt','ucBankAcc_ucLookupBank_uclBank_hd1','BCA','ucBankAcc_ucLookupBank_uclBank_hd2','251');;overlay('mdnucBankAcc_ucLookupBank_uclBank');</value>
      <webElementGuid>b8e7591c-2f1b-4659-943a-09faaea6289e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>48caccbf-5bf1-493b-9457-0c70a5755b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>fcd8dc34-ba6a-499b-91a2-0e8d1711539f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Loan Data/iframe_Term  Condition_appForm</value>
      <webElementGuid>384c5d4f-60a6-4753-970a-de5595aff2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>d18221c9-8edb-412f-abeb-574c58f04203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>2ad7a859-e6c1-43e7-8a31-2b13b266aa4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>d57ac2e3-5c38-41f7-9b48-b13f339ca95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA'])[1]/following::a[1]</value>
      <webElementGuid>1043dbec-a1d7-49ed-862e-d03619028cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[2]/following::a[1]</value>
      <webElementGuid>a8fc8a8e-98ee-420b-8138-9fc45ef80667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[2]/preceding::a[1]</value>
      <webElementGuid>dfd8547c-3064-4585-96b4-f6f12ea2b385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>63ba990c-4e2d-4a4b-b9c1-032f7d286d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:BankLookup('ucBankAcc_ucLookupBank_uclBank_txt','ucBankAcc_ucLookupBank_uclBank_hd1','BCA','ucBankAcc_ucLookupBank_uclBank_hd2','251');;overlay('mdnucBankAcc_ucLookupBank_uclBank');&quot;)]</value>
      <webElementGuid>5577a109-506e-4cfc-91ab-30218fb727d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>fa4beadd-c6bb-430a-a1fb-5380f83df6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucBankAcc_ucLookupBank_uclBank_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:BankLookup(&quot; , &quot;'&quot; , &quot;ucBankAcc_ucLookupBank_uclBank_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucBankAcc_ucLookupBank_uclBank_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;BCA&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucBankAcc_ucLookupBank_uclBank_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;251&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucBankAcc_ucLookupBank_uclBank&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>3b454842-6839-4c64-9211-3dd3d4cfcad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
