<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Num Of Asset</name>
   <tag></tag>
   <elementGuidId>4b8dc96a-6e9e-4300-8e18-ecd1e0e98d09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucINNumOfAsset_txtInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucINNumOfAsset_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINNumOfAsset_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucINNumOfAsset_txtInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b46ecd9-0358-4010-aa49-96ae3bef989c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINNumOfAsset$txtInput</value>
      <webElementGuid>aa879a47-d4ef-4eb1-b1b1-0dfcd87e5d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c163ffef-7bd0-4a9a-a501-250de2fe5df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINNumOfAsset_txtInput</value>
      <webElementGuid>07050264-7884-441a-9d00-33e1526b626b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
      <webElementGuid>0ce3f194-bf15-4d24-ba25-a8fa851a32a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValueInteger('ucINNumOfAsset_txtInput','ucINNumOfAsset_hdnInput','ucINNumOfAsset_txtInputDummy');</value>
      <webElementGuid>bc9bc4c7-a29e-48f2-81d4-7deb68bf28cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINNumOfAsset_txtInput');</value>
      <webElementGuid>72a94c27-3dc6-415d-9e68-0ca30d32b5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>ad3c0925-a5fe-4b56-bead-d80c7f6f9e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINNumOfAsset_txtInput&quot;)</value>
      <webElementGuid>7f5d423c-e9a2-4ac2-870d-e9ab045e6341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Add New Application Mobil/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>69a0a994-fb67-4666-a961-ab6cce7bcc75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINNumOfAsset_txtInput']</value>
      <webElementGuid>1524ab4d-bbe6-4b90-84fa-fced10d91d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trNumOfAsset']/td[2]/input[2]</value>
      <webElementGuid>25cbbcec-60f2-46c4-b023-0e5a2014f394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input[2]</value>
      <webElementGuid>a8360243-9fb7-4931-8ba9-39c578d5e2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINNumOfAsset$txtInput' and @type = 'text' and @id = 'ucINNumOfAsset_txtInput']</value>
      <webElementGuid>9ea3e05f-8954-46f1-a983-40a494ddd5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
