<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_treeContainer</name>
   <tag></tag>
   <elementGuidId>a447fbf7-f04b-415b-930b-4495a6ea0afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treeContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='treeContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#treeContainer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7cbf9957-c91f-48f0-a6c0-6954c90138e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>NewTree.aspx</value>
      <webElementGuid>aa130d88-a26b-4e56-b6c7-a25d796bb779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeContainer</value>
      <webElementGuid>503e6587-7bed-4f7a-bb78-f325cdd1ea79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0407f073-fda1-49ad-8e0c-692f2a776878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeContainer&quot;)</value>
      <webElementGuid>f7bff50f-d6e1-4fea-933f-eff780d4e594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='treeContainer']</value>
      <webElementGuid>8e808834-07f4-44aa-9115-46d2f466c287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[2]</value>
      <webElementGuid>e93e52a4-a564-4f1e-b414-260a09d99dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>2eb9d851-6edf-40f1-9ec1-20d2fafb232c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'NewTree.aspx' and @id = 'treeContainer']</value>
      <webElementGuid>8d451202-cfaf-4d91-b0f3-3c960f511653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
